### ISSUE TITLE
看到篇文章说资源文件用减号“-”比较好，有点儿困惑，请教一下～=￣ω￣=～

### ISSUE THREAD

**Issue by BuptStEve** [AlloyTeam/CodeGuide#4]
文件/资源命名

在 web 项目中，所有的文件名应该都遵循同一命名约定。以可读性而言，减号（-）是用来分隔文件名的不二之选。同时它也是常见的 URL 分隔符（i.e. //example.com/blog/my-blog-entry or //s.example.com/images/big-black-background.jpg），所以理所当然的，减号应该也是用来分隔资源名称的好选择。

来源： https://github.com/gionkunz/chartist-js/blob/develop/CODINGSTYLE.md

**Comment by iazrael** [comment]
命名一直是编程史上的大难题， 我们永远也没办法统一全世界的命名规则， 但是作为一个团队， 绝对是不能允许一个项目有各式各样的名字的， 所以其实不管是什么样的规则， 只要**有规则**就可以了。

我们这里用下划线`_`而不是减号`-`的出发点是这样的：

1。 项目名用下划线， 可以很方便的在命令行执行一些构建命令， 如 `grunt xxx_yyy`， 如果是减号， 则需要 `grunt 'xxx-yyy'`
2。 基于上面的原因， 项目名字用下划线， 文件名用减号， 也是挺混乱的， 所以干脆都统一了， 开发者不需要太多思考

规范本身应该成为一种开发习惯， 越简单越容易执行越好。 当然全部文件命名都用减号也是可以的， 只要团队过半的成员都认同即可。

**Comment by BuptStEve** [comment]
ok, I see ～=￣ω￣=～
